# Generated by Django 5.0.4 on 2024-05-19 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.TextField(max_length=200)),
                ('password', models.TextField(default='12345')),
            ],
            options={
                'verbose_name': 'Аккаунт',
                'verbose_name_plural': 'Аккаунты',
            },
        ),
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Questioner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_url', models.TextField()),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('address', models.TextField()),
                ('telephone', models.TextField(max_length=200)),
                ('site', models.TextField()),
                ('balance', models.FloatField()),
                ('account', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.account')),
            ],
            options={
                'verbose_name': 'Опросник',
                'verbose_name_plural': 'Опросники',
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('resources', models.TextField()),
                ('body', models.JSONField()),
                ('description', models.TextField()),
                ('reward', models.FloatField()),
                ('start_date', models.DateTimeField()),
                ('expiration_date', models.DateTimeField()),
                ('creation_date', models.DateField()),
                ('last_updated', models.DateField()),
                ('questioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.questioner')),
            ],
            options={
                'verbose_name': 'Форма',
                'verbose_name_plural': 'Формы',
            },
        ),
        migrations.CreateModel(
            name='Respondent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('avatar_url', models.TextField()),
                ('first_name', models.TextField()),
                ('second_name', models.TextField()),
                ('patronymic', models.TextField()),
                ('gender', models.TextField()),
                ('birthday', models.DateField()),
                ('education_level', models.CharField(choices=[('B', 'Bachelor'), ('M', 'Master'), ('P', 'PhD')], max_length=1)),
                ('about_me', models.TextField()),
                ('balance', models.FloatField()),
                ('creation_time', models.DateField()),
                ('last_updated', models.DateTimeField()),
                ('account', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.account')),
                ('hobbies', models.ManyToManyField(to='user.hobby')),
            ],
            options={
                'verbose_name': 'Ответчик',
                'verbose_name_plural': 'Ответчики',
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('result', models.JSONField()),
                ('creation_time', models.TimeField()),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.form')),
                ('respondent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.respondent')),
            ],
            options={
                'verbose_name': 'Опрос',
                'verbose_name_plural': 'Опросы',
            },
        ),
    ]
